version: '3'

services:
  influxdb:
    image: influxdb:latest
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8082:8082"
    environment:
      - INFLUXDB_USER="shake"
      - INFLUXDB_USER_PASSWORD="yabooty"
    networks:
      - tick

  chronograf:
    image: chronograf:latest
    volumes:
      - ./chronograf/data:/var/lib/chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
    networks:
      - tick

networks:
  tick: